version: '3.8'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=proyecto_informatico
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1' | mysql -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} proyecto_informatico || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  flask:
    build:
      context: ./proyecto_backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=flaskr
      - FLASK_PORT=5000
      - FLASK_HOST=0.0.0.0
      - LOG_LEVEL=INFO
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=your_password
      - MYSQL_DB=proyecto_informatico
      - MYSQL_CURSORCLASS=DictCursor
      - USE_FLASK_MYSQLDB=true
      - CORS_ORIGINS=https://proyecto_frontend.test,http://proyecto_frontend.test,http://localhost,https://localhost,http://127.0.0.1,https://127.0.0.1
      - CORS_METHODS=GET,POST,PUT,DELETE
      - CORS_ALLOW_HEADERS=Content-Type,Authorization
      - SSL_CERTFILE=./flaskr/ssl/cert.pem
      - SSL_KEYFILE=./flaskr/ssl/key.pem
      - SECRET_KEY=6bec47eaa7caa760b7ce01e85740d98076c179d3f93c7b664e3c7c350a7df189
    restart: always

  apache:
    build:
      context: ./proyecto_frontend
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: always

volumes:
  mariadb_data: